import { Link } from "wouter";

type Card = { index: string; label: string; title: string; copy: string; meta?: string };

type Props = { eyebrow: string; title: React.ReactNode; intro: string; cards: readonly Card[]; accent?: "blue" | "warm" };

const links = [
  ["/work", "WORK"], ["/builds", "BUILDS"], ["/creative", "CREATIVE"], ["/products", "PRODUCTS"], ["/strategy", "STRATEGY"], ["/experience", "EXPERIENCE"], ["/story", "STORY"], ["/certifications", "CERTIFICATIONS"], ["/recognition", "RECOGNITION"], ["/lab", "LAB"], ["/toolbox", "TOOLBOX"], ["/cv", "CV"], ["/contact", "CONTACT"],
];

export default function UniversePage({ eyebrow, title, intro, cards, accent = "blue" }: Props) {
  return <main className={`inner-page ${accent}`}>
    <header className="inner-topbar"><Link href="/" className="wordmark"><span className="mark">A</span><span>ASHRAF<br /><small>SALISU MOHAMMED</small></span></Link><Link href="/" className="back-link">← INDEX</Link></header>
    <div className="inner-layout"><aside className="inner-sidebar"><p className="eyebrow">DIRECTORY</p>{links.map(([href, label], i) => <Link key={href} href={href}><span>0{i + 1}</span>{label}</Link>)}</aside><section className="inner-content"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="inner-intro">{intro}</p><div className="inner-grid">{cards.map((card) => <article className="inner-card" key={card.index}><div className="inner-card-top"><span>{card.index}</span><span>{card.meta || "ARCHIVE / 2026"}</span></div><div className="inner-card-art"><span>{card.label}</span></div><p className="card-label">{card.label}</p><h2>{card.title}</h2><p>{card.copy}</p><div className="card-line" /></article>)}</div></section></div><footer className="footer"><span>© 2026 ASHRAF SALISU MOHAMMED</span><span>BUILDING ACROSS FOUR DIMENSIONS</span></footer>
  </main>;
}

export const pageData = {
  work: { eyebrow: "01 / THE WORK", title: <>A portfolio with<br /><em>more than one language.</em></>, intro: "The full body of work, separated into distinct universes so that a product is not confused with a website, and a company is not confused with a project.", cards: [{ index: "01", label: "PRODUCTS", title: "Carevo — healthcare from home.", copy: "A virtual hospital and healthcare ecosystem connecting patients, practitioners, pharmacy and laboratory services.", meta: "FEATURED CASE STUDY" }, { index: "02", label: "WEB / SOFTWARE", title: "Digital systems with a point of view.", copy: "Websites, applications and technical builds shown as work rather than a list of tools." }, { index: "03", label: "CREATIVE", title: "Visual language that makes a message move.", copy: "Graphic design, video editing, content and experimental direction." }, { index: "04", label: "BRAND & STRATEGY", title: "The thinking behind the thing.", copy: "Positioning, partnerships, growth initiatives and the bridge from concept to traction." }] },
  builds: { eyebrow: "02 / WEBSITES I’VE BUILT", title: <>Digital work<br /><em>you can experience.</em></>, intro: "A separate archive for websites, software, applications and technical experiments. Real screenshots, videos, live URLs and repositories will be added from the verified project archive.", cards: [{ index: "01", label: "WEBSITE", title: "Project archive slot", copy: "Screenshot, role, design contribution, development contribution, technology, problem, solution and live URL to be added from verified records.", meta: "MEDIA NEEDED" }, { index: "02", label: "APPLICATION", title: "Software project slot", copy: "A place for an actual application or system, with its story told through interface footage and technical detail.", meta: "MEDIA NEEDED" }, { index: "03", label: "EXPERIMENT", title: "Creative technology slot", copy: "Small apps, interfaces and technical experiments that show how Ashraf thinks by making." }] },
  creative: { eyebrow: "03 / VISUAL WORK", title: <>Make the message<br /><em>visible.</em></>, intro: "A visual archive for graphic design, posters, social media, campaigns, typography, editorial systems, technology and experimental work.", accent: "warm", cards: [{ index: "01", label: "GRAPHIC DESIGN", title: "Dark editorial systems.", copy: "Posters, campaign graphics, structured information panels and technology-led visual direction." }, { index: "02", label: "VIDEO EDITING", title: "Motion with intention.", copy: "Short-form video, promotional content, social media video and creative experiments. Video archive to be added." }, { index: "03", label: "CONTENT", title: "Ideas made shareable.", copy: "YouTube, social content, creative writing and campaign content. Channel link and embeds to be added." }] },
  products: { eyebrow: "04 / PRODUCTS & STARTUPS", title: <>Build the thing<br /><em>people can use.</em></>, intro: "Products and startup initiatives remain separate from companies worked with and websites built. Each product gets its own case-study language.", cards: [{ index: "01", label: "CAREVO", title: "Healthcare from the comfort of home.", copy: "700+ practitioners, 3,000+ patients, consultations, pharmacy, laboratory services and an ecosystem vision across Africa.", meta: "MAJOR CASE STUDY" }, { index: "02", label: "CAREPOINTS", title: "A partnership and social-impact concept.", copy: "A points system connected to healthcare access and support for young women. Presented as a concept, not an outcome claim." }, { index: "03", label: "STARTUP ARCHIVE", title: "More products, verified one by one.", copy: "Demasking, Nexalife, Kevo / Zelora-related concepts and other documented initiatives will enter after archive review." }] },
  strategy: { eyebrow: "05 / BRAND & STRATEGY", title: <>The thinking<br /><em>behind the build.</em></>, intro: "From idea to brand to product to technology to growth. This is where the business layer of Ashraf’s work becomes visible.", cards: [{ index: "01", label: "POSITIONING", title: "Give the idea a place to stand.", copy: "Brand strategy, product positioning, digital strategy and strategic planning." }, { index: "02", label: "PARTNERSHIPS", title: "Build the network around the product.", copy: "Partnership development, fundraising support, networking and ecosystem integration." }, { index: "03", label: "GROWTH", title: "Make the next move make sense.", copy: "Business development, growth initiatives, startup strategy and content strategy." }] },
  experience: { eyebrow: "06 / EXPERIENCE", title: <>A journey through<br /><em>different rooms.</em></>, intro: "Not a résumé timeline. A record of progression—from creative execution into content, technology, products, strategy and leadership responsibilities.", cards: [{ index: "2024", label: "RECOVERY HUB", title: "Graphic Designer → Content Manager", copy: "July 8, 2024 – February 17, 2025. Graphic design, content management, digital content and audience engagement. Volunteer of the Year." }, { index: "2024", label: "VY CHAIN QUANTUM BLOCKCHAIN", title: "Lead Developer", copy: "September–December 2024. Blockchain and technology development." }, { index: "2025", label: "STRANO GLOBAL", title: "Freelancer", copy: "Freelance work through September 2025. Exact project archive to be added." }, { index: "2026", label: "XELORRA INNOVATIONS", title: "Business Development Partner → CCO responsibilities", copy: "Strategic partnerships, business development, planning, growth initiatives and Carevo ecosystem integration." }] },
  story: { eyebrow: "07 / HOW I GOT HERE", title: <>Started by creating.<br />Learned to build.<br /><em>Now I build across all four.</em></>, intro: "Graphic design led toward digital work. Digital work led toward development. Development led toward product building. Product building led toward startups and business.", cards: [{ index: "01", label: "CREATIVITY", title: "The first instinct was to make.", copy: "Visual communication, posters, design systems, content and experiments." }, { index: "02", label: "TECHNOLOGY", title: "Then came the systems.", copy: "Web technologies, software engineering, APIs and the curiosity to understand how things work." }, { index: "03", label: "PRODUCT + BUSINESS", title: "Then came the reason.", copy: "Products, startups, partnerships, positioning and the work of making ideas tangible." }] },
  certifications: { eyebrow: "08 / CERTIFICATION ARCHIVE", title: <>Learning is part of<br /><em>the build.</em></>, intro: "A dedicated archive for certificates and learning credentials. Certificate images, metadata and download links will be added from the verified files.", cards: [{ index: "01", label: "UDEMY", title: "Mastering React", copy: "October 22, 2025. Certificate image and credential link to be added." }, { index: "02", label: "TECHNICAL", title: "Linux for Data Engineering", copy: "Certificate metadata and file to be added." }, { index: "03", label: "TECHNICAL", title: "Data Science and AI Mastery", copy: "Certificate metadata and file to be added." }, { index: "04", label: "MTF INSTITUTE", title: "Executive Diplomas", copy: "Verified certificate list to be added." }] },
  recognition: { eyebrow: "09 / RECOGNITION", title: <>Proof of<br /><em>motion.</em></>, intro: "Achievements, hackathons and notable moments shown as recognition—not buried in a résumé.", cards: [{ index: "02", label: "2ND PLACE", title: "Africa’s Talking Real Estate Hackathon", copy: "April 2026." }, { index: "RU", label: "RUNNER-UP", title: "Dabo Hackathon", copy: "December 2025. Prize: ₦200,000." }, { index: "08", label: "8TH PLACE", title: "Kasitda Hackathon", copy: "September 2025." }, { index: "V", label: "VOLUNTEER OF THE YEAR", title: "Recovery Hub", copy: "Documented recognition." }, { index: "NASA", label: "ALUMNI", title: "NASA Space Apps", copy: "Alumni status." }] },
  lab: { eyebrow: "10 / THE LAB", title: <>Things built when<br /><em>nobody asked.</em></>, intro: "Experimental interfaces, AI experiments, design experiments, small apps, prototypes, unfinished ideas and creative coding.", cards: [{ index: "01", label: "PROTOTYPE", title: "Open slot for a strange idea.", copy: "The lab is allowed to be less corporate. Real experiments will be added from the archive." }, { index: "02", label: "AI EXPERIMENT", title: "A place to test the future.", copy: "Experiments in tools, interfaces and new ways of working." }, { index: "03", label: "CREATIVE CODE", title: "Motion, systems, play.", copy: "Small builds that communicate curiosity more than polish." }] },
  toolbox: { eyebrow: "11 / TOOLBOX", title: <>Tools are not the story.<br /><em>What they unlock is.</em></>, intro: "An honest categorical view of the technical and creative tools Ashraf uses—without arbitrary percentage bars.", cards: [{ index: "01", label: "DEVELOPMENT", title: "JavaScript / TypeScript / React / Node.js", copy: "HTML, CSS, Bootstrap, PHP and Laravel." }, { index: "02", label: "DATA + SERVICES", title: "MongoDB / Firebase / Supabase / PostgreSQL", copy: "API integration, AI API integration, DNS and indexing." }, { index: "03", label: "CREATIVE", title: "Figma / Canva / Adobe", copy: "Graphic design, visual systems, video editing and content workflows." }, { index: "04", label: "CLOUD + COLLABORATION", title: "Git / GitHub / AWS / Azure", copy: "VS Code and the systems around shipping work." }] },
  cv: { eyebrow: "12 / CV", title: <>The concise<br /><em>version.</em></>, intro: "The portfolio is the long-form world. The CV is the compressed view. The latest approved CV will be connected here once supplied.", cards: [{ index: "01", label: "SUMMARY", title: "Multidisciplinary Developer, Creative, Product Builder & Strategist", copy: "Computer Science student at Northwest University, Kano. 300 Level." }, { index: "02", label: "EDUCATION", title: "BSc Computer Science — Northwest University", copy: "Current level: 300 Level. GPA: 3.5." }, { index: "03", label: "DOWNLOAD", title: "Approved CV file", copy: "The latest approved document will be attached here. No second résumé will be generated." }] },
  contact: { eyebrow: "13 / CONTACT", title: <>Let’s build<br /><em>something.</em></>, intro: "For products, creative direction, strategy, software, content or the idea that does not fit neatly anywhere yet.", cards: [{ index: "01", label: "EMAIL", title: "[EMAIL NEEDED]", copy: "Verified contact address to be added." }, { index: "02", label: "GITHUB", title: "791BOTLYKCODES", copy: "Exact URL to be verified before publishing." }, { index: "03", label: "LINKEDIN / X / YOUTUBE", title: "Professional links", copy: "Verified URLs and YouTube channel link to be added." }] },
} as const;
